In [2]:
import pandas as pd

In [32]:
for index,row in df2.iterrows():
    participant=row['ID']
    ontology = row['Ontologies']
    Visualization = row['Visualization']
    Task_Sucess = row['Task_Success']
    Time_On_Task = row['Time_On_Task']
    
    print(participant,ontology,Visualization,Time_On_Task)
    string1 = ("D:\Data Visualisation\Archive"+"\\" +participant+ "\\"+ participant+".graphFXD.txt")
    #string2= (string1 + "\\" + participant  + participant + '.graphFXD.txt')
    print(string1)         
    df = pd.read_csv(string1, sep="\t",header=None)
    df.columns=['No', 'Time', 'Duration', 'Screen X', 'Screen Y']                
    df[['participant','Ontologies','Visualization','Task_Sucess','Time_On_Task']] = pd.DataFrame([[participant,ontology,Visualization,Task_Sucess,Time_On_Task]],index = df.index)
    df.to_csv("D:/Data Visualisation/newFileSarita/"+participant+".csv")                
                     
                     
                     #df_all_cols = pd.concat([df, df2], axis = 1)
   #print (row['ID'], row['Ontologies'])

p2 1 2 19
D:\Data Visualisation\Archive\p2\p2.graphFXD.txt
p4 1 2 12
D:\Data Visualisation\Archive\p4\p4.graphFXD.txt
p6 1 2 26
D:\Data Visualisation\Archive\p6\p6.graphFXD.txt
p10 1 2 17
D:\Data Visualisation\Archive\p10\p10.graphFXD.txt
p12 1 2 17
D:\Data Visualisation\Archive\p12\p12.graphFXD.txt
p14 1 2 15
D:\Data Visualisation\Archive\p14\p14.graphFXD.txt
p16 1 2 28
D:\Data Visualisation\Archive\p16\p16.graphFXD.txt
p18 1 2 21
D:\Data Visualisation\Archive\p18\p18.graphFXD.txt
p20 1 2 30
D:\Data Visualisation\Archive\p20\p20.graphFXD.txt
p24 1 2 32
D:\Data Visualisation\Archive\p24\p24.graphFXD.txt
p28 1 2 10
D:\Data Visualisation\Archive\p28\p28.graphFXD.txt
p30 1 2 23
D:\Data Visualisation\Archive\p30\p30.graphFXD.txt
p32 1 2 21
D:\Data Visualisation\Archive\p32\p32.graphFXD.txt
p34 1 2 38
D:\Data Visualisation\Archive\p34\p34.graphFXD.txt
p36 1 2 21
D:\Data Visualisation\Archive\p36\p36.graphFXD.txt

In [ ]:
df = pd.read_csv("D:\Data Visualisation\Archive\"+participant+"\"+ participant+".graphFXD.txt", sep="\t",header=None)

In [174]:
df

       0       1    2     3    4
0      1     475  100   632  405
1      2    4084  100   285  197
2      3    4622  339    72  208
3      4    7792  199   304  978
4      5    8490  120   389  915
5      6    8669  100   405  917
6      7    9267  100    77  195
7      8    9387  379    71  212
8      9    9945  219   273  216
9     10   12876  100  1054  774
10    11   14611  199  1072  749
11    12   15867  120  1046  785
12    13   19615  140   279  201
13    14   20313  139   248  223
14    15   20472  100   269  177
15    16   20612  100   297  181
16    17   27690  179    83  190
17    18   28407  159   277  995
18    19   30640  160   388  903
19    20   31577  120   425  901
20    21   32933  120   408  838
21    22   42802  100   281  241
22    23   43600  100   304  186
23    24   46331  199   425  183
24    25   46550  100   433  197
25    26   46770  179   505  182
26    27   47966  120   701  283
27    28   49322  120   266  215
28    29   53927  100   995  898
29    30   59928  100   420  864
..   ...     ...  ...   ...  ...
575  576  653049  140   518  256
576  577  653727  100   442  206
577  578  658452  140    78  262
578  579  660286  199   438  282
579  580  660605  100   448  283
580  581  662579  140    67  201
581  582  668002  319    67  234
582  583  679247  140  1167  670
583  584  680104  100  1160  686
584  585  683613  100  1075  561
585  586  684590  120   240  205
586  587  685288  120   384  207
587  588  688657  120   459  179
588  589  690372  100   431  215
589  590  690830  140   420  236
590  591  698586  100   126  308
591  592  700002  299   888  859
592  593  704946  120   857  905
593  594  706721  120   843  942
594  595  707299  100   385  337
595  596  711087  100   460  257
596  597  711885  100   592  241
597  598  715254  100   233  293
598  599  716889  140    46  221
599  600  717108  399    42  205
600  601  718823  100   143  162
601  602  719760  100   669  182
602  603  720936  100   480  121
603  604  722750  179  1084  120
604  605  723568  179  1060  114

[605 rows x 5 columns]

In [175]:
df.columns=['No', 'Time', 'Duration', 'Screen X', 'Screen Y']

In [176]:
df

      No    Time  Duration  Screen X  Screen Y
0      1     475       100       632       405
1      2    4084       100       285       197
2      3    4622       339        72       208
3      4    7792       199       304       978
4      5    8490       120       389       915
5      6    8669       100       405       917
6      7    9267       100        77       195
7      8    9387       379        71       212
8      9    9945       219       273       216
9     10   12876       100      1054       774
10    11   14611       199      1072       749
11    12   15867       120      1046       785
12    13   19615       140       279       201
13    14   20313       139       248       223
14    15   20472       100       269       177
15    16   20612       100       297       181
16    17   27690       179        83       190
17    18   28407       159       277       995
18    19   30640       160       388       903
19    20   31577       120       425       901
20    21   32933       120       408       838
21    22   42802       100       281       241
22    23   43600       100       304       186
23    24   46331       199       425       183
24    25   46550       100       433       197
25    26   46770       179       505       182
26    27   47966       120       701       283
27    28   49322       120       266       215
28    29   53927       100       995       898
29    30   59928       100       420       864
..   ...     ...       ...       ...       ...
575  576  653049       140       518       256
576  577  653727       100       442       206
577  578  658452       140        78       262
578  579  660286       199       438       282
579  580  660605       100       448       283
580  581  662579       140        67       201
581  582  668002       319        67       234
582  583  679247       140      1167       670
583  584  680104       100      1160       686
584  585  683613       100      1075       561
585  586  684590       120       240       205
586  587  685288       120       384       207
587  588  688657       120       459       179
588  589  690372       100       431       215
589  590  690830       140       420       236
590  591  698586       100       126       308
591  592  700002       299       888       859
592  593  704946       120       857       905
593  594  706721       120       843       942
594  595  707299       100       385       337
595  596  711087       100       460       257
596  597  711885       100       592       241
597  598  715254       100       233       293
598  599  716889       140        46       221
599  600  717108       399        42       205
600  601  718823       100       143       162
601  602  719760       100       669       182
602  603  720936       100       480       121
603  604  722750       179      1084       120
604  605  723568       179      1060       114

[605 rows x 5 columns]

In [ ]:
p1	2	2	0.52173913	38

In [19]:
df.insert(column() "Participant")

SyntaxError: invalid syntax (<ipython-input-19-021cacc553c7>, line 1)

In [3]:
df2 = pd.read_csv("D:\Data Visualisation\Asgn2\o1v2.csv")

df2

     ID  Ontologies  Visualization  Task_Success  Time_On_Task
0    p2           1              2      0.347826            19
1    p4           1              2      0.391304            12
2    p6           1              2      0.869565            26
3   p10           1              2      0.608696            17
4   p12           1              2      0.304348            17
5   p14           1              2      0.521739            15
6   p16           1              2      0.521739            28
7   p18           1              2      0.739130            21
8   p20           1              2      0.391304            30
9   p24           1              2      0.565217            32
10  p28           1              2      0.521739            10
11  p30           1              2      0.391304            23
12  p32           1              2      0.304348            21
13  p34           1              2      0.608696            38
14  p36           1              2      0.434783            21

In [184]:
string = df2.iloc[:,0]
print(string)

0      p2
1      p4
2      p6
3     p10
4     p12
5     p14
6     p16
7     p18
8     p20
9     p24
10    p28
11    p30
12    p32
13    p34
14    p36
Name: ID, dtype: object

In [ ]:
df.assign(**{'col_new_1': np.nan, 'col2_new_2': 'dogs', 'col3_new_3': 3})

In [ ]:
p3
2
2
0.391304
50

In [179]:
df[['participant','Ontologies','Visualization','Task_Sucess','Time_On_Task']] = pd.DataFrame([['p4','1','2','0.391304','12']],index = df.index)

In [180]:
df

,No,Time,Duration,Screen X,Screen Y,participant,Ontologies,Visualization,Task_Sucess,Time_On_Task
0,1,475,100,632,405,p4,1,2,0.391304,12
1,2,4084,100,285,197,p4,1,2,0.391304,12
2,3,4622,339,72,208,p4,1,2,0.391304,12
3,4,7792,199,304,978,p4,1,2,0.391304,12
4,5,8490,120,389,915,p4,1,2,0.391304,12
5,6,8669,100,405,917,p4,1,2,0.391304,12
6,7,9267,100,77,195,p4,1,2,0.391304,12
7,8,9387,379,71,212,p4,1,2,0.391304,12
8,9,9945,219,273,216,p4,1,2,0.391304,12
9,10,12876,100,1054,774,p4,1,2,0.391304,12
10,11,14611,199,1072,749,p4,1,2,0.391304,12
11,12,15867,120,1046,785,p4,1,2,0.391304,12
12,13,19615,140,279,201,p4,1,2,0.391304,12
13,14,20313,139,248,223,p4,1,2,0.391304,12
14,15,20472,100,269,177,p4,1,2,0.391304,12
15,16,20612,100,297,181,p4,1,2,0.391304,12
16,17,27690,179,83,190,p4,1,2,0.391304,12
17,18,28407,159,277,995,p4,1,2,0.391304,12
18,19,30640,160,388,903,p4,1,2,0.391304,12
19,20,31577,120,425,901,p4,1,2,0.391304,12
20,21,32933,120,408,838,p4,1,2,0.391304,12
21,22,42802,100,281,241,p4,1,2,0.391304,12
22,23,43600,100,304,186,p4,1,2,0.391304,12
23,24,46331,199,425,183,p4,1,2,0.391304,12
24,25,46550,100,433,197,p4,1,2,0.391304,12
25,26,46770,179,505,182,p4,1,2,0.391304,12
26,27,47966,120,701,283,p4,1,2,0.391304,12
27,28,49322,120,266,215,p4,1,2,0.391304,12
28,29,53927,100,995,898,p4,1,2,0.391304,12
29,30,59928,100,420,864,p4,1,2,0.391304,12
...,...,...,...,...,...,...,...,...,...,...
575,576,653049,140,518,256,p4,1,2,0.391304,12
576,577,653727,100,442,206,p4,1,2,0.391304,12
577,578,658452,140,78,262,p4,1,2,0.391304,12
578,579,660286,199,438,282,p4,1,2,0.391304,12
579,580,660605,100,448,283,p4,1,2,0.391304,12
580,581,662579,140,67,201,p4,1,2,0.391304,12
581,582,668002,319,67,234,p4,1,2,0.391304,12
582,583,679247,140,1167,670,p4,1,2,0.391304,12
583,584,680104,100,1160,686,p4,1,2,0.391304,12
584,585,683613,100,1075,561,p4,1,2,0.391304,12
585,586,684590,120,240,205,p4,1,2,0.391304,12
586,587,685288,120,384,207,p4,1,2,0.391304,12
587,588,688657,120,459,179,p4,1,2,0.391304,12
588,589,690372,100,431,215,p4,1,2,0.391304,12
589,590,690830,140,420,236,p4,1,2,0.391304,12
590,591,698586,100,126,308,p4,1,2,0.391304,12
591,592,700002,299,888,859,p4,1,2,0.391304,12
592,593,704946,120,857,905,p4,1,2,0.391304,12
593,594,706721,120,843,942,p4,1,2,0.391304,12
594,595,707299,100,385,337,p4,1,2,0.391304,12
595,596,711087,100,460,257,p4,1,2,0.391304,12
596,597,711885,100,592,241,p4,1,2,0.391304,12
597,598,715254,100,233,293,p4,1,2,0.391304,12
598,599,716889,140,46,221,p4,1,2,0.391304,12
599,600,717108,399,42,205,p4,1,2,0.391304,12
600,601,718823,100,143,162,p4,1,2,0.391304,12
601,602,719760,100,669,182,p4,1,2,0.391304,12
602,603,720936,100,480,121,p4,1,2,0.391304,12
603,604,722750,179,1084,120,p4,1,2,0.391304,12
604,605,723568,179,1060,114,p4,1,2,0.391304,12

In [181]:
df.to_csv("D:/Data Visualisation/Asgn2/fixp4.csv")

In [ ]:
data_frames= []

In [33]:
df = pd.read_csv("D:\\Data Visualisation\\newFileShraddha\\groupO1V1.csv")
df

          X     Y  dilation
0      1005    60    3.7745
1        78   237    3.7175
2       246   207    3.6625
3       298   198    3.6650
4       909  1002    3.6195
5       507   559    3.7810
6      1012   986    3.6555
7      1046   997    3.6755
8       739   584    3.8295
9        90   592    3.7470
10       83   612    3.6430
11       58   485    3.5885
12      311   175    3.5195
13       79   201    3.5675
14       66   232    3.4925
15       64   230    3.4475
16      240   205    3.5230
17       62   202    3.4500
18       88   566    3.5755
19       90   542    3.6350
20       95   534    3.6130
21       85   590    3.6350
22       95   600    3.6975
23      185   158    3.6635
24       96   599    3.6215
25       89   535    3.7020
26       83   517    3.6645
27      720   544    3.6670
28      934   974    3.4505
29      764   282    3.4975
...     ...   ...       ...
32946   687   648    3.9065
32947   728   627    4.0005
32948   728   612    4.0380
32949   730   606    3.9805
32950   772   660    3.9940
32951   695   613    4.1415
32952   731   648    4.3265
32953   274   192    3.7445
32954   760   638    3.7885
32955   781   672    4.0930
32956   782   774    4.0985
32957   748   785    4.2105
32958   725   652    4.1255
32959   738   623    4.1035
32960   742   618    3.9700
32961    67   585    3.7560
32962   474   266    3.6650
32963   458   221    3.6415
32964   515   192    3.7570
32965   502   200    4.0320
32966   506   206    3.9335
32967   617   211    4.0060
32968   613   212    4.1050
32969   531   242    4.1650
32970   514   273    4.1285
32971   443   205    4.0720
32972   296   268    3.8760
32973   685   564    4.0395
32974   148   581    4.0970
32975    50   566    4.1020

[32976 rows x 3 columns]

In [37]:
df['dilation'].mean()

3.8669230197719626